### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by MartinPankraz** [Soontao/cds-mysql#13]
Hey Soontao,

this project is awesome. Any chance you could add SSL support? I am running MariaDB on Azure and needed to switch off "Enforce SSL connection" to run your module. My local client required only "Use SSL" as configuration with no further specifications. Looks like a local cer file would do the trick for even more sophisticated setups:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/5108923/147480713-cfc331b2-47ba-42a3-aeed-7aa6712dfd13.png">

<img width="759" alt="image" src="https://user-images.githubusercontent.com/5108923/147481249-58423066-12c5-4cfd-9ecb-617f091f767a.png">

Once I switch off the enforcement

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5108923/147481345-3c8b7526-d234-470d-8b0f-ea9c7be04cb7.png">

your scripts finish successfully

Adding "use SSL" to your config would be a good starting point :-)

KR
Martin

**Comment by Soontao** [comment]
Hi @MartinPankraz 

Sure, thanks for your suggestion, I'll provide this feature after my vacation. 

thanks for your contribution.

Regards,
Theo

**Comment by Soontao** [comment]
Hi @MartinPankraz 

I've provided an example which include the `SSL` configuration, just check [this document](https://github.com/Soontao/odata-v4-cap-demo#by-default-envjson-local-development-only)

You need to upgrade the `cds-mysql` to the latest version (above 5.9.2).

Just let me know if you have any other query, and, have a nice day :) 


Regards,
Theo

**Comment by MartinPankraz** [comment]
Hey @Soontao,

thanks for the quick upgrade! I tested locally with Azure DB for MySQL and added the cert to the .env file like so:

CDS_MYSQL_SSL_CA=-----BEGIN CERTIFICATE-----MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ\nRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD***\n-----END CERTIFICATE-----\n

In addition to that I checked different flavors without \n or the cert prefix etc. without any luck. Am I missing something? 

My error is: [mysql] - Error: unable to get local issuer certificate - HANDSHAKE_SSL_ERROR

KR
Martin

**Comment by Soontao** [comment]
Hi @MartinPankraz 

sorry this is a bug, please try the new version `5.9.3`, and please double quoted the certificate string like:

```bash
CDS_MYSQL_SSL_CA="-----BEGIN CERTIFICATE-----\n ... \n-----END CERTIFICATE-----\n"
```

Regards,
Theo

**Comment by MartinPankraz** [comment]
Awesome, that works now. Also with TLS1.2 enforced.

KR
Martin
