### ISSUE TITLE
[BUG] scripts  deploy [mysql] - Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by 974758241** [Soontao/cds-mysql#29]
![image](https://user-images.githubusercontent.com/24804009/174261667-558135f2-897f-4bd7-83e3-682816f0db90.png)
我想本地化开发,发现运行 deploy脚本  报错

**Comment by Soontao** [comment]
Hi @974758241 

whats your credential? for the simple setup mysql server, please remove the credentials.ssl node from default-env.json(because its not enabled by sever side)

Regards,
Theo

**Comment by 974758241** [comment]
![image](https://user-images.githubusercontent.com/24804009/174280099-cb3b1315-1f62-4241-b5d8-865b4ac44387.png)
难道不是更具我的CDS 文件,生成对应表名称和字段吗

**Comment by Soontao** [comment]
Hi@974758241 

did the "cap" database has been created in your local mysql instance?

for your question, yes, it seems you checkout a demo repo for cds-mysql, just remove the pre-defined entity definition in db/srv folders to remove them.

Regards,
Theo
